export const states = [
  'Alabama',
  'Alaska',
  'American Samoa',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'District Of Columbia',
  'Federated States Of Micronesia',
  'Florida',
  'Georgia',
  'Guam',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Marshall Islands',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Northern Mariana Islands',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Palau',
  'Pennsylvania',
  'Puerto Rico',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virgin Islands',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
];

export const ReportSectionHeaders = [
  {
    questionId: 16,
    description: 'PREVIOUS POLYGRAPH EXAMS',
  },
  {
    questionId: 22,
    description: 'ACCURACY OF ALL INFORMATION PROVIDED TO THIS DEPARTMENT',
  },
  {
    questionId: 24,
    description: 'CHEATING ON EXAMINATIONS FOR THIS DEPARTMENT',
  },
  {
    questionId: 27,
    description: 'EMPLOYMENT INTENTIONS',
  },
  {
    questionId: 42,
    description: 'DRIVING RECORD',
  },
  {
    questionId: 49,
    description: 'EDUCATION',
  },
  {
    questionId: 57,
    description: 'EMPLOYMENT TERMINATIONS',
  },
  {
    questionId: 64,
    description: 'DISCIPLINARY ACTIONS',
  },
  {
    questionId: 81,
    description: 'MILITARY HISTORY',
  },
  {
    questionId: 83,
    description: `CRIMINAL HISTORY/RECORD`,
  },
  {
    questionId: 85,
    description: `SERIOUS UNDETECTED CRIMES`,
  },
  {
    questionId: 95,
    description: `ILLEGAL DRUG USE`,
  },
  {
    questionId: 97,
    description: `ILLEGAL DRUG SALES/DISTRIBUTION`,
  },
  {
    questionId: 100,
    description: `EMPLOYMENT THEFTS (Property for the last 10 years)`,
  },
  {
    questionId: 103,
    description: `EMPLOYMENT THEFTS (Money for the last 10 years)`,
  },
  {
    questionId: 107,
    description: `THEFTS (Other than from an employer in the last 10 years)`,
  },
  {
    questionId: 110,
    description: `PERPETRATING ACTS OF PHYSICAL/MENTAL ABUSE`,
  },
  {
    questionId: 112,
    description: `PREJUDICE`,
  },
  {
    questionId: 114,
    description: `ILLEGAL FIRE SETTING (FOR FIRE APPLICANTS ONLY)`,
  },

  {
    questionId: 117,
    description: `VIOLATING LAWS OR REGULATIONS REGARDING PARKS AND WILDLIFE RULES (FOR CPW APPLICANTS ONLY)`,
  },
  {
    questionId: 120,
    description: `ABUSE OF LAW ENFORCEMENT POWERS`,
  },
  {
    questionId: 122,
    description: `PERPETRATING ACTS OF ILLEGAL SEXUAL ACTIVITIES`,
  },
  {
    questionId: 131,
    description: `DEROGATORY FINANCIAL INFORMATION`,
  },
  {
    questionId: 132,
    description: 'ADDITIONAL NOTES BY EXAMINER',
  },
];
